require("./js/egret.js")
require("./js/eui.js")
require("./js/assetsmanager.js")
require("./js/tween.js")
require("./js/game.js")
require("./js/egretad.js")
require("./js/main.js")
require("./js/default.thm.js")